---
# Install Packages using the APT Package Manager
- hosts: glusterfs
  tasks:
  - name: Install Packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - ntp
      - python
      - tcpdump
      - wget
      - openssl
      - curl
      - glusterfs-server 
      - glusterfs-client 
      - glusterfs-common 
      - nfs-kernel-server
