---
# Provisions User on Nodes
# Setup Passwordless SSH from Jumpbox
# Install Packages using APT
- name: setup pre-requisites
  hosts: new
  roles:
    - create-sudo-user
    - install-modules
    - configure-hosts-file

- name: setup ruan user on the nodes
  become: yes
  become_user: ruan
  hosts: admin
  roles:
    - configure-admin

- name: copy public key to nodes
  become: yes
  become_user: ruan
  hosts: new
  roles:
    - copy-keys
