---
# Return Host Vars
# Return Variables
- hosts: admin
  tasks:
  - debug:
      msg: "Host: {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

  - debug:
      msg: "Host: {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }} and IP {{ ansible_default_ipv4.address }}"
    when: ansible_default_ipv4.gateway is defined

  - name: register uptime
    shell: /usr/bin/uptime
    register: result

  - debug: msg="{{result.stdout}}"
  - debug: var=result['stdout']
  - debug: msg="{{result['stdout']}}"

  - debug: 
      var: hostvars[inventory_hostname]['ansible_nodename']

  - name: print info
    vars:
      msg: |
        Country: {{ location_country }}
        City: {{ location_city }}
    debug:
      msg: "{{ msg.split('\n') }}"
    tags: debug_info
