---
# Provisions User on Nodes
# Setup Passwordless SSH from Jumpbox
# Install Packages using APT
- name: setup pre-requisites
  hosts: elasticsearch
  roles:
    - create-sudo-user
    - install-modules
    - configure-hosts-file

- name: copy public key to nodes
  become: yes
  become_user: ruan
  hosts: elasticsearch
  roles:
    - copy-keys

- name: install elasticsearch
  hosts: elasticsearch
  roles:
    - elasticsearch
